# Generated by Django 4.1.2 on 2023-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics')], max_length=256, unique=True),
        ),
    ]
