# Generated by Django 4.1.2 on 2023-06-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0002_alter_subjects_subject_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('standard', 'mon_1')},
        ),
    ]
