# Generated by Django 4.1.2 on 2023-06-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0006_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fri_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_1_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_2_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_3_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_4_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_5_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_1_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_2_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_3_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_4_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_5_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thurs_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thurs_1_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thurs_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thurs_2_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thurs_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thurs_3_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thurs_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thurs_4_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thurs_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thurs_5_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tue_1_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tue_2_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tue_3_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tue_4_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tue_5_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednes_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wed_1_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednes_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wed_2_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednes_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wed_3_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednes_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wed_4_subject_teacher', to='TimeTableApp.teachers'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednes_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wed_5_subject_teacher', to='TimeTableApp.teachers'),
        ),
    ]
