# Generated by Django 4.1.2 on 2023-07-01 17:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0007_alter_timetable_fri_1_alter_timetable_fri_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teaches_for_class',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=256),
        ),
    ]
