# Generated by Django 4.1.2 on 2023-07-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableApp', '0008_alter_teachers_teaches_for_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Test Subject', 'Test Subject')], max_length=256, unique=True),
        ),
    ]
